### ISSUE TITLE
I can't install on ionic 5

### ISSUE THREAD

**Issue by dacgxcustomer** [amicaldo/cordova-plugin-kiosk-mode#3]
I get an error when I want to install the plugin in ionic 5

`No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "https://github.com/amicaldo/cordova-plugin-kiosk-mode"
fetch: Installing https://github.com/amicaldo/cordova-plugin-kiosk-mode to E:\Xcustomer360\apps\XcustomerAppCleanKiosko
Running command: npm install https://github.com/amicaldo/cordova-plugin-kiosk-mode --save-dev
Command finished with error code 4294963238: npm install,https://github.com/amicaldo/cordova-plugin-kiosk-mode,--save-dev
Failed to fetch plugin https://github.com/amicaldo/cordova-plugin-kiosk-mode via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 4294963238 Error output:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/amicaldo/cordova-plugin-kiosk-mode.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\the_e\AppData\Roaming\npm-cache\_logs\2021-04-28T17_29_01_044Z-debug.log
CordovaError: Failed to fetch plugin https://github.com/amicaldo/cordova-plugin-kiosk-mode via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 4294963238 Error output:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/amicaldo/cordova-plugin-kiosk-mode.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\the_e\AppData\Roaming\npm-cache\_logs\2021-04-28T17_29_01_044Z-debug.log
    at C:\Users\the_e\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:140:43
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

Thanks for you reply

**Comment by TomCosta** [comment]
Please, have you solved this?

**Comment by JannikHv** [comment]
Which command did you enter exactly to get this output?
